BootStrap: docker
From: nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04

%labels

%environment
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
export PATH=/bin:/usr/bin:/usr/local/bin:/usr/local/cuda/bin:
export LC_ALL=C

%post
apt-get update
apt-get install -y libhdf5-dev graphviz locales python3-dev python3-pip
apt-get clean

pip3 install tensorflow-gpu==1.8.0
pip3 install keras==2.1.6
pip3 install numpy Pillow scikit-learn pandas\
 matplotlib notebook ipython h5py liac-arff openpyxl xlsxwriter

# create some generic mount points
mkdir -p /var/spool/slurm
mkdir /cvmfs /grid /data1 /data2 /data0
touch /bin/nvidia-smi
# jost and nsc
mkdir -p /net/jost/home /d/hpc/session /d/hpc/cache
mkdir -p /net/hold/data1
